version: '3.7'

services:
  database:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    restart: 'on-failure'
    volumes:
      - postgres_data:/pgdata

volumes:
  postgres_data:
  minio_data:

networks:
  api:
    driver: bridge
